from collections import namedtuple

#HOST
IP = '127.0.0.1'
PORT = 14580

#MAVLINK PAYLOAD PARSE
MESSAGECODES = {0: namedtuple('HEARTBEAT', 'type autopilot base_mode custom_mode system_status mavlink_version'),
                1: namedtuple('SYS_STATUS',
                              'onboard_control_sensors_present onboard_control_sensors_enabled onboard_control_sensors_health load voltage_battery current_battery battery_remaining drop_rate_comm error_comm error_count1 error_count2 error_count3 error_count4'),
                2: namedtuple('SYSTEM_TIME', 'time_unix_usec time_boot_ms'),
                4: namedtuple('PING', 'time_usec seq target_system target_component'),
                8: namedtuple('LINK_NODE_STATUS',
                              'timestamp tx_buf rx_buf tx_rate rx_rate rx_parse_err tx_overflows rx_overflows messages_sent messages_received messages_lost'),
                24: namedtuple('GPS_RAW_INT', 'time_usec fix_type lat lon alt eph epv vel cog satellites_visible'),
                30: namedtuple('ATTITUDE', 'time_boot_ms roll pitch yaw rollspeed pitchspeed yawspeed'),
                31: namedtuple('ATTITUDE_QUATERNION', 'time_boot_ms q1 q2 q3 q4 rollspeed pitchspeed yawspeed'),
                32: namedtuple('LOCAL_POSITION_NED', 'time_boot_ms x y z vx vy vz'),
                33: namedtuple('GLOBAL_POSITION_INT', 'time_boot_ms lat lon alt relative_alt vx vy vz hdg'),
                36: namedtuple('SERVO_OUTPUT_RAW',
                               'time_usec port servo1_raw servo2_raw servo3_raw servo4_raw servo5_raw servo6_raw servo7_raw servo8_raw'),
                49: namedtuple('GPS_GLOBAL_ORIGIN', 'latitude longitude altitude'),
                74: namedtuple('VFR_HUD', 'airspeed groundspeed heading throttle alt climb'),
                83: namedtuple('ATTITUDE_TARGET',
                               'time_boot_ms type_mask q1 q2 q3 q4 body_roll_rate body_pitch_rate body_yaw_rate thrust'),
                85: namedtuple('POSITION_TARGET_LOCAL_NED',
                               'time_boot_ms coordinate_frame type_mask x y z vx vy vz afx afy afz yaw yaw_rate'),
                105: namedtuple('HIGHRES_IMU',
                                'time_usec xacc yacc zacc xgyro ygyro zgyro xmag ymag zmag abs_pressure diff_pressure pressure_alt temperature fields_updated'),
                111: namedtuple('TIMESYNC', 'tc1 ts1'),
                140: namedtuple('ACTUATOR_CONTROL_TARGET',
                                'time_usec group_mlx controls1 controls2 controls3 controls4 controls5 controls6 controls7 controls8'),
                141: namedtuple('ALTITUDE',
                                'time_usec altitude_monotonic altitude_amsl altitude_local altitude_relative altitude_terrain bottom_clearance'),
                147: namedtuple('BATTERY_STATUS',
                                'id battery_function type temperature voltages1 voltages2 voltages3 voltages4 voltages5 voltages6 voltages7 voltages8 voltages9 voltages10 current_battery current_consumed energy_consumed battery_remaining'),
                230: namedtuple('ESTIMATOR_STATUS',
                                'time_usec flags vel_ratio pos_horiz_ratio pos_vert_ratio mag_ratio hagl_ratio tas_ratio pos_horiz_accuracy pos_vert_accuracy'),
                241: namedtuple('VIBRATION',
                                'time_usec vibration_x vibration_y vibration_z clipping_0 clipping_1 clipping_2'),
                242: namedtuple('HOME_POSITION',
                                'latitude longitude altitude x y z q1 q2 q3 q4 approach_x approach_y approach_z'),
                245: namedtuple('EXTENDED_SYS_STATE', 'vtol_state landed_state')

                }
MAVLINKFORMATS = {0: '!BBBIBB',
                  1: '!IIIHHhbHHHHHH',
                  2: '!QL',
                  4: '!QLBB',
                  8: '!QBBIIHHHIII',
                  24: '!QBIIIHHHHB',
                  30: '!Iffffff',
                  31: '!Ifffffff',
                  32: '!Iffffff',
                  33: '!IiiiihhhH',
                  36: '!IBHHHHHHHH',
                  49: '!III',
                  74: '!ffhHff',
                  83: '!Ibffffffff',
                  85: '!IBHfffffffffff',
                  105: '!QfffffffffffffH',
                  111: '!qq',
                  140: '!QBffffffff',
                  141: '!Qffffff',
                  147: '!BBBhHHHHHHHHHHhiib',
                  230: '!QHffffffff',
                  241: '!QfffIII',
                  242: '!iiiffffffffff',
                  245: '!BB'
                  }
